// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Directory {

  /// <summary>Holder for reflection information generated from service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1zZXJ2aWNlLnByb3RvEglEaXJlY3RvcnkaDHBsYXllci5wcm90bxoIaWQu",
            "cHJvdG8y3AEKCURpcmVjdG9yeRIvCglHZXRQbGF5ZXISDS5EaXJlY3Rvcnku",
            "SUQaES5EaXJlY3RvcnkuUGxheWVyIgASNgoMVXBkYXRlUGxheWVyEhEuRGly",
            "ZWN0b3J5LlBsYXllchoRLkRpcmVjdG9yeS5QbGF5ZXIiABI2CgxDcmVhdGVQ",
            "bGF5ZXISES5EaXJlY3RvcnkuUGxheWVyGhEuRGlyZWN0b3J5LlBsYXllciIA",
            "Ei4KDERlbGV0ZVBsYXllchINLkRpcmVjdG9yeS5JRBoNLkRpcmVjdG9yeS5J",
            "RCIAQg1aCy47ZGlyZWN0b3J5YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Directory.PlayerReflection.Descriptor, global::Directory.IdReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
