// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: entities_row.proto

package deviant

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type EntitiesRow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entities []*Entity `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
}

func (x *EntitiesRow) Reset() {
	*x = EntitiesRow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entities_row_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntitiesRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntitiesRow) ProtoMessage() {}

func (x *EntitiesRow) ProtoReflect() protoreflect.Message {
	mi := &file_entities_row_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntitiesRow.ProtoReflect.Descriptor instead.
func (*EntitiesRow) Descriptor() ([]byte, []int) {
	return file_entities_row_proto_rawDescGZIP(), []int{0}
}

func (x *EntitiesRow) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

var File_entities_row_proto protoreflect.FileDescriptor

var file_entities_row_proto_rawDesc = []byte{
	0x0a, 0x12, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x5f, 0x72, 0x6f, 0x77, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x44, 0x65, 0x76, 0x69, 0x61, 0x6e, 0x74, 0x1a, 0x0c, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3a, 0x0a, 0x0b, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x6f, 0x77, 0x12, 0x2b, 0x0a, 0x08, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x44,
	0x65, 0x76, 0x69, 0x61, 0x6e, 0x74, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x08, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x69, 0x65, 0x73, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x3b, 0x64, 0x65, 0x76,
	0x69, 0x61, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_entities_row_proto_rawDescOnce sync.Once
	file_entities_row_proto_rawDescData = file_entities_row_proto_rawDesc
)

func file_entities_row_proto_rawDescGZIP() []byte {
	file_entities_row_proto_rawDescOnce.Do(func() {
		file_entities_row_proto_rawDescData = protoimpl.X.CompressGZIP(file_entities_row_proto_rawDescData)
	})
	return file_entities_row_proto_rawDescData
}

var file_entities_row_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_entities_row_proto_goTypes = []interface{}{
	(*EntitiesRow)(nil), // 0: Deviant.EntitiesRow
	(*Entity)(nil),      // 1: Deviant.Entity
}
var file_entities_row_proto_depIdxs = []int32{
	1, // 0: Deviant.EntitiesRow.entities:type_name -> Deviant.Entity
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_entities_row_proto_init() }
func file_entities_row_proto_init() {
	if File_entities_row_proto != nil {
		return
	}
	file_entity_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_entities_row_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntitiesRow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entities_row_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_entities_row_proto_goTypes,
		DependencyIndexes: file_entities_row_proto_depIdxs,
		MessageInfos:      file_entities_row_proto_msgTypes,
	}.Build()
	File_entities_row_proto = out.File
	file_entities_row_proto_rawDesc = nil
	file_entities_row_proto_goTypes = nil
	file_entities_row_proto_depIdxs = nil
}
