// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: card_action_targeting_types.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Deviant {

  /// <summary>Holder for reflection information generated from card_action_targeting_types.proto</summary>
  public static partial class CardActionTargetingTypesReflection {

    #region Descriptor
    /// <summary>File descriptor for card_action_targeting_types.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CardActionTargetingTypesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiFjYXJkX2FjdGlvbl90YXJnZXRpbmdfdHlwZXMucHJvdG8SB0RldmlhbnQq",
            "MAoYQ2FyZEFjdGlvblRhcmdldGluZ1R5cGVzEggKBFBBVEgQABIKCgZHUk9V",
            "TkQQAUILWgkuO2RldmlhbnRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Deviant.CardActionTargetingTypes), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum CardActionTargetingTypes {
    [pbr::OriginalName("PATH")] Path = 0,
    [pbr::OriginalName("GROUND")] Ground = 1,
  }

  #endregion

}

#endregion Designer generated code
