// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Classes.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Deviant {

  /// <summary>Holder for reflection information generated from Classes.proto</summary>
  public static partial class ClassesReflection {

    #region Descriptor
    /// <summary>File descriptor for Classes.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClassesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1DbGFzc2VzLnByb3RvEgdEZXZpYW50KjYKB0NsYXNzZXMSCwoHV0FSUklP",
            "UhAAEggKBE1BR0UQARIKCgZQUklFU1QQAhIICgRXQUxMEANCC1oJLjtkZXZp",
            "YW50YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Deviant.Classes), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum Classes {
    [pbr::OriginalName("WARRIOR")] Warrior = 0,
    [pbr::OriginalName("MAGE")] Mage = 1,
    [pbr::OriginalName("PRIEST")] Priest = 2,
    [pbr::OriginalName("WALL")] Wall = 3,
  }

  #endregion

}

#endregion Designer generated code
