// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: conditions.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Deviant {

  /// <summary>Holder for reflection information generated from conditions.proto</summary>
  public static partial class ConditionsReflection {

    #region Descriptor
    /// <summary>File descriptor for conditions.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ConditionsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBjb25kaXRpb25zLnByb3RvEgdEZXZpYW50KhYKCkNvbmRpdGlvbnMSCAoE",
            "U0xPVxAAQgtaCS47ZGV2aWFudGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Deviant.Conditions), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum Conditions {
    [pbr::OriginalName("SLOW")] Slow = 0,
  }

  #endregion

}

#endregion Designer generated code
