// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: encounter_service.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Deviant {
  public static partial class EncounterService
  {
    static readonly string __ServiceName = "Deviant.EncounterService";

    static readonly grpc::Marshaller<global::Deviant.EncounterRequest> __Marshaller_Deviant_EncounterRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Deviant.EncounterRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Deviant.EncounterResponse> __Marshaller_Deviant_EncounterResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Deviant.EncounterResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Deviant.EncounterRequest, global::Deviant.EncounterResponse> __Method_UpdateEncounter = new grpc::Method<global::Deviant.EncounterRequest, global::Deviant.EncounterResponse>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "UpdateEncounter",
        __Marshaller_Deviant_EncounterRequest,
        __Marshaller_Deviant_EncounterResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Deviant.EncounterServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of EncounterService</summary>
    [grpc::BindServiceMethod(typeof(EncounterService), "BindService")]
    public abstract partial class EncounterServiceBase
    {
      public virtual global::System.Threading.Tasks.Task UpdateEncounter(grpc::IAsyncStreamReader<global::Deviant.EncounterRequest> requestStream, grpc::IServerStreamWriter<global::Deviant.EncounterResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for EncounterService</summary>
    public partial class EncounterServiceClient : grpc::ClientBase<EncounterServiceClient>
    {
      /// <summary>Creates a new client for EncounterService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public EncounterServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for EncounterService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public EncounterServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected EncounterServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected EncounterServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncDuplexStreamingCall<global::Deviant.EncounterRequest, global::Deviant.EncounterResponse> UpdateEncounter(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateEncounter(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncDuplexStreamingCall<global::Deviant.EncounterRequest, global::Deviant.EncounterResponse> UpdateEncounter(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_UpdateEncounter, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override EncounterServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new EncounterServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(EncounterServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_UpdateEncounter, serviceImpl.UpdateEncounter).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, EncounterServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_UpdateEncounter, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::Deviant.EncounterRequest, global::Deviant.EncounterResponse>(serviceImpl.UpdateEncounter));
    }

  }
}
#endregion
