// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: entity_target_action_types.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Deviant {

  /// <summary>Holder for reflection information generated from entity_target_action_types.proto</summary>
  public static partial class EntityTargetActionTypesReflection {

    #region Descriptor
    /// <summary>File descriptor for entity_target_action_types.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EntityTargetActionTypesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiBlbnRpdHlfdGFyZ2V0X2FjdGlvbl90eXBlcy5wcm90bxIHRGV2aWFudCo5",
            "ChdFbnRpdHlUYXJnZXRBY3Rpb25UeXBlcxIOCgpUQVJHRVRNT1ZFEAASDgoK",
            "VEFSR0VUQ0FSRBABQgtaCS47ZGV2aWFudGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Deviant.EntityTargetActionTypes), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EntityTargetActionTypes {
    [pbr::OriginalName("TARGETMOVE")] Targetmove = 0,
    [pbr::OriginalName("TARGETCARD")] Targetcard = 1,
  }

  #endregion

}

#endregion Designer generated code
