// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: EntityMoveAction.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Deviant {

  /// <summary>Holder for reflection information generated from EntityMoveAction.proto</summary>
  public static partial class EntityMoveActionReflection {

    #region Descriptor
    /// <summary>File descriptor for EntityMoveAction.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EntityMoveActionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZFbnRpdHlNb3ZlQWN0aW9uLnByb3RvEgdEZXZpYW50InIKEEVudGl0eU1v",
            "dmVBY3Rpb24SFgoOc3RhcnRYUG9zaXRpb24YASABKAUSFgoOc3RhcnRZUG9z",
            "aXRpb24YAiABKAUSFgoOZmluYWxYUG9zaXRpb24YAyABKAUSFgoOZmluYWxZ",
            "UG9zaXRpb24YBCABKAVCC1oJLjtkZXZpYW50YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Deviant.EntityMoveAction), global::Deviant.EntityMoveAction.Parser, new[]{ "StartXPosition", "StartYPosition", "FinalXPosition", "FinalYPosition" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class EntityMoveAction : pb::IMessage<EntityMoveAction> {
    private static readonly pb::MessageParser<EntityMoveAction> _parser = new pb::MessageParser<EntityMoveAction>(() => new EntityMoveAction());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EntityMoveAction> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Deviant.EntityMoveActionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityMoveAction() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityMoveAction(EntityMoveAction other) : this() {
      startXPosition_ = other.startXPosition_;
      startYPosition_ = other.startYPosition_;
      finalXPosition_ = other.finalXPosition_;
      finalYPosition_ = other.finalYPosition_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EntityMoveAction Clone() {
      return new EntityMoveAction(this);
    }

    /// <summary>Field number for the "startXPosition" field.</summary>
    public const int StartXPositionFieldNumber = 1;
    private int startXPosition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StartXPosition {
      get { return startXPosition_; }
      set {
        startXPosition_ = value;
      }
    }

    /// <summary>Field number for the "startYPosition" field.</summary>
    public const int StartYPositionFieldNumber = 2;
    private int startYPosition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StartYPosition {
      get { return startYPosition_; }
      set {
        startYPosition_ = value;
      }
    }

    /// <summary>Field number for the "finalXPosition" field.</summary>
    public const int FinalXPositionFieldNumber = 3;
    private int finalXPosition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int FinalXPosition {
      get { return finalXPosition_; }
      set {
        finalXPosition_ = value;
      }
    }

    /// <summary>Field number for the "finalYPosition" field.</summary>
    public const int FinalYPositionFieldNumber = 4;
    private int finalYPosition_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int FinalYPosition {
      get { return finalYPosition_; }
      set {
        finalYPosition_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EntityMoveAction);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EntityMoveAction other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StartXPosition != other.StartXPosition) return false;
      if (StartYPosition != other.StartYPosition) return false;
      if (FinalXPosition != other.FinalXPosition) return false;
      if (FinalYPosition != other.FinalYPosition) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StartXPosition != 0) hash ^= StartXPosition.GetHashCode();
      if (StartYPosition != 0) hash ^= StartYPosition.GetHashCode();
      if (FinalXPosition != 0) hash ^= FinalXPosition.GetHashCode();
      if (FinalYPosition != 0) hash ^= FinalYPosition.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StartXPosition != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(StartXPosition);
      }
      if (StartYPosition != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(StartYPosition);
      }
      if (FinalXPosition != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(FinalXPosition);
      }
      if (FinalYPosition != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(FinalYPosition);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StartXPosition != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StartXPosition);
      }
      if (StartYPosition != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StartYPosition);
      }
      if (FinalXPosition != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FinalXPosition);
      }
      if (FinalYPosition != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(FinalYPosition);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EntityMoveAction other) {
      if (other == null) {
        return;
      }
      if (other.StartXPosition != 0) {
        StartXPosition = other.StartXPosition;
      }
      if (other.StartYPosition != 0) {
        StartYPosition = other.StartYPosition;
      }
      if (other.FinalXPosition != 0) {
        FinalXPosition = other.FinalXPosition;
      }
      if (other.FinalYPosition != 0) {
        FinalYPosition = other.FinalYPosition;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            StartXPosition = input.ReadInt32();
            break;
          }
          case 16: {
            StartYPosition = input.ReadInt32();
            break;
          }
          case 24: {
            FinalXPosition = input.ReadInt32();
            break;
          }
          case 32: {
            FinalYPosition = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
