// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: EntityRotationNames.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Deviant {

  /// <summary>Holder for reflection information generated from EntityRotationNames.proto</summary>
  public static partial class EntityRotationNamesReflection {

    #region Descriptor
    /// <summary>File descriptor for EntityRotationNames.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EntityRotationNamesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlFbnRpdHlSb3RhdGlvbk5hbWVzLnByb3RvEgdEZXZpYW50Kj8KE0VudGl0",
            "eVJvdGF0aW9uTmFtZXMSCQoFTk9SVEgQABIJCgVTT1VUSBABEggKBEVBU1QQ",
            "AhIICgRXRVNUEANCC1oJLjtkZXZpYW50YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Deviant.EntityRotationNames), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EntityRotationNames {
    [pbr::OriginalName("NORTH")] North = 0,
    [pbr::OriginalName("SOUTH")] South = 1,
    [pbr::OriginalName("EAST")] East = 2,
    [pbr::OriginalName("WEST")] West = 3,
  }

  #endregion

}

#endregion Designer generated code
