// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: turn_phase_names.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Deviant {

  /// <summary>Holder for reflection information generated from turn_phase_names.proto</summary>
  public static partial class TurnPhaseNamesReflection {

    #region Descriptor
    /// <summary>File descriptor for turn_phase_names.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TurnPhaseNamesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZ0dXJuX3BoYXNlX25hbWVzLnByb3RvEgdEZXZpYW50KncKDlR1cm5QaGFz",
            "ZU5hbWVzEg8KC1BIQVNFX1BPSU5UEAASEAoMUEhBU0VfRUZGRUNUEAESDgoK",
            "UEhBU0VfRFJBVxACEhAKDFBIQVNFX0FDVElPThADEhEKDVBIQVNFX0RJU0NB",
            "UkQQBBINCglQSEFTRV9FTkQQBUILWgkuO2RldmlhbnRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Deviant.TurnPhaseNames), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum TurnPhaseNames {
    [pbr::OriginalName("PHASE_POINT")] PhasePoint = 0,
    [pbr::OriginalName("PHASE_EFFECT")] PhaseEffect = 1,
    [pbr::OriginalName("PHASE_DRAW")] PhaseDraw = 2,
    [pbr::OriginalName("PHASE_ACTION")] PhaseAction = 3,
    [pbr::OriginalName("PHASE_DISCARD")] PhaseDiscard = 4,
    [pbr::OriginalName("PHASE_END")] PhaseEnd = 5,
  }

  #endregion

}

#endregion Designer generated code
