// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: TurnPhaseNames.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Deviant {

  /// <summary>Holder for reflection information generated from TurnPhaseNames.proto</summary>
  public static partial class TurnPhaseNamesReflection {

    #region Descriptor
    /// <summary>File descriptor for TurnPhaseNames.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TurnPhaseNamesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRUdXJuUGhhc2VOYW1lcy5wcm90bxIHRGV2aWFudCp3Cg5UdXJuUGhhc2VO",
            "YW1lcxIPCgtQSEFTRV9QT0lOVBAAEhAKDFBIQVNFX0VGRkVDVBABEg4KClBI",
            "QVNFX0RSQVcQAhIQCgxQSEFTRV9BQ1RJT04QAxIRCg1QSEFTRV9ESVNDQVJE",
            "EAQSDQoJUEhBU0VfRU5EEAVCC1oJLjtkZXZpYW50YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Deviant.TurnPhaseNames), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum TurnPhaseNames {
    [pbr::OriginalName("PHASE_POINT")] PhasePoint = 0,
    [pbr::OriginalName("PHASE_EFFECT")] PhaseEffect = 1,
    [pbr::OriginalName("PHASE_DRAW")] PhaseDraw = 2,
    [pbr::OriginalName("PHASE_ACTION")] PhaseAction = 3,
    [pbr::OriginalName("PHASE_DISCARD")] PhaseDiscard = 4,
    [pbr::OriginalName("PHASE_END")] PhaseEnd = 5,
  }

  #endregion

}

#endregion Designer generated code
