// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Attachment.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Deviant {

  /// <summary>Holder for reflection information generated from Attachment.proto</summary>
  public static partial class AttachmentReflection {

    #region Descriptor
    /// <summary>File descriptor for Attachment.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AttachmentReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBBdHRhY2htZW50LnByb3RvEgdEZXZpYW50KhQKCkF0dGFjaG1lbnQSBgoC",
            "SUQQAEIJWgdkZXZpYW50YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Deviant.Attachment), }, null));
    }
    #endregion

  }
  #region Enums
  public enum Attachment {
    [pbr::OriginalName("ID")] Id = 0,
  }

  #endregion

}

#endregion Designer generated code
