// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: CardType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Deviant {

  /// <summary>Holder for reflection information generated from CardType.proto</summary>
  public static partial class CardTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for CardType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CardTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5DYXJkVHlwZS5wcm90bxIHRGV2aWFudCpGCghDYXJkVHlwZRIKCgZBVFRB",
            "Q0sQABIICgRCVUZGEAESCgoGREVCVUZGEAISCgoGU1VNTU9OEAMSDAoITU9W",
            "RU1FTlQQBEIJWgdkZXZpYW50YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Deviant.CardType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum CardType {
    [pbr::OriginalName("ATTACK")] Attack = 0,
    [pbr::OriginalName("BUFF")] Buff = 1,
    [pbr::OriginalName("DEBUFF")] Debuff = 2,
    [pbr::OriginalName("SUMMON")] Summon = 3,
    [pbr::OriginalName("MOVEMENT")] Movement = 4,
  }

  #endregion

}

#endregion Designer generated code
