// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: EntityActionNames.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Deviant {

  /// <summary>Holder for reflection information generated from EntityActionNames.proto</summary>
  public static partial class EntityActionNamesReflection {

    #region Descriptor
    /// <summary>File descriptor for EntityActionNames.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EntityActionNamesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdFbnRpdHlBY3Rpb25OYW1lcy5wcm90bxIHRGV2aWFudCppChFFbnRpdHlB",
            "Y3Rpb25OYW1lcxIICgRQTEFZEAASCAoETU9WRRABEggKBERSQVcQAhILCgdE",
            "SVNDQVJEEAMSCwoHTk9USElORxAEEhAKDENIQU5HRV9QSEFTRRAFEgoKBlJP",
            "VEFURRAGQglaB2RldmlhbnRiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Deviant.EntityActionNames), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum EntityActionNames {
    [pbr::OriginalName("PLAY")] Play = 0,
    [pbr::OriginalName("MOVE")] Move = 1,
    [pbr::OriginalName("DRAW")] Draw = 2,
    [pbr::OriginalName("DISCARD")] Discard = 3,
    [pbr::OriginalName("NOTHING")] Nothing = 4,
    [pbr::OriginalName("CHANGE_PHASE")] ChangePhase = 5,
    [pbr::OriginalName("ROTATE")] Rotate = 6,
  }

  #endregion

}

#endregion Designer generated code
