// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: EntityActionNames.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Deviant {

  /// <summary>Holder for reflection information generated from EntityActionNames.proto</summary>
  public static partial class EntityActionNamesReflection {

    #region Descriptor
    /// <summary>File descriptor for EntityActionNames.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EntityActionNamesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdFbnRpdHlBY3Rpb25OYW1lcy5wcm90bxIHRGV2aWFudCpTChFFbnRpdHlB",
            "Y3Rpb25OYW1lcxIICgRQTEFZEAASCAoERFJBVxABEgsKB0RJU0NBUkQQAhIL",
            "CgdOT1RISU5HEAMSEAoMQ0hBTkdFX1BIQVNFEARCCVoHZGV2aWFudGIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Deviant.EntityActionNames), }, null));
    }
    #endregion

  }
  #region Enums
  public enum EntityActionNames {
    [pbr::OriginalName("PLAY")] Play = 0,
    [pbr::OriginalName("DRAW")] Draw = 1,
    [pbr::OriginalName("DISCARD")] Discard = 2,
    [pbr::OriginalName("NOTHING")] Nothing = 3,
    [pbr::OriginalName("CHANGE_PHASE")] ChangePhase = 4,
  }

  #endregion

}

#endregion Designer generated code
