name: Protobuf Code Autogeneration

on:
  push:
    paths:
    - 'protobuf/**/*'
  pull_request:
    paths:
    - 'protobuf/**/*'
jobs:
  genproto:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        path: deviant-protobuf
        token: ${{ secrets.RECLUSE_CI_ROBOT_TOKEN }}

    # Setup Environment
    - name: set latest protoc release tag
      run: |
        export LATEST_PROTOC_TAG=$(curl --silent https://api.github.com/repos/protocolbuffers/protobuf/releases/latest | grep '"tag_name":' | cut -d'"' -f4 | cut -c2-)
        echo "::set-env name=PROTOC_TAG::$LATEST_PROTOC_TAG"

    # Download the latest Protoc release
    - name: download protoc
      run: curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v${{ env.PROTOC_TAG }}/protoc-${{ env.PROTOC_TAG }}-linux-x86_64.zip
    
    # Unzip Protoc
    - name: unzip protoc
      run: unzip protoc-${{ env.PROTOC_TAG }}-linux-x86_64.zip -d protoc

    # Add Protoc to System Path
    - name: append to path
      run: echo "::add-path::protoc/bin"

    # Install protoc gen from go
    - name: install protoc gen
      run: |
        go get github.com/golang/protobuf/protoc-gen-go
        export GO_BIN_PATH=$(go env GOPATH)/bin
        echo "::add-path::$GO_BIN_PATH"

    # Generate the protocol buffers using protoc.
    - name: Generate Go Protocol Buffers
      run: |
        protoc --proto_path='deviant-protobuf/protobuf/packages/directory/' --go_out=plugins=grpc:deviant-protobuf/genproto/go/directory/ deviant-protobuf/protobuf/packages/directory/*.proto
        protoc --proto_path='deviant-protobuf/protobuf/packages/instance_shard/' --go_out=plugins=grpc:deviant-protobuf/genproto/go/instance_shard deviant-protobuf/protobuf/packages/instance_shard/*.proto

    - name: Generate C# Protocol Buffers
      run: |
        curl -L https://www.nuget.org/api/v2/package/Grpc.Tools/ -o /tmp/grpctools.zip 
        unzip -o /tmp/grpctools.zip -d /tmp/grpctools/
        chmod +x /tmp/grpctools/tools/linux_x64/protoc
        chmod +x /tmp/grpctools/tools/linux_x64/grpc_csharp_plugin

        /tmp/grpctools/tools/linux_x64/protoc --plugin=protoc-gen-grpc=/tmp/grpctools/tools/linux_x64/grpc_csharp_plugin --proto_path='deviant-protobuf/protobuf/packages/directory/' --csharp_out=deviant-protobuf/genproto/cs/directory --grpc_out=deviant-protobuf/genproto/cs/directory/  deviant-protobuf/protobuf/packages/directory/*.proto
        /tmp/grpctools/tools/linux_x64/protoc --plugin=protoc-gen-grpc=/tmp/grpctools/tools/linux_x64/grpc_csharp_plugin --proto_path='deviant-protobuf/protobuf/packages/instance_shard/' --csharp_out=deviant-protobuf/genproto/cs/instance_shard --grpc_out=deviant-protobuf/genproto/cs/instance_shard/  deviant-protobuf/protobuf/packages/instance_shard/*.proto


    - uses: stefanzweifel/git-auto-commit-action@v4.1.6
      with:
        commit_message: Apply automatic changes

        # Optional name of the branch the commit should be pushed to
        # Required if Action is used in Workflow listening to the `pull_request` event.
        # Also required for almost all other events (eg. `schedule`)
        branch: ${{ github.head_ref }}

        # Optional git params
        commit_options: '--no-verify --signoff'

        # Optional glob pattern of files which should be added to the commit
        file_pattern: genproto/go/**/*.pb.go genproto/cs/**/*.cs

        # Optional local file path to the repository
        repository: deviant-protobuf

        # Optional commit user and author settings
        commit_user_name: recluse-ci-robot
        commit_user_email: opensource@recluse-games.com
        commit_author: recluse-ci-robot <opensource@recluse-games.com>
