name: Protobuf Code Autogeneration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  genproto:
    runs-on: golang-alpine
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: generate protobufs
      run: apk add protoc && ./genproto.sh

    - uses: stefanzweifel/git-auto-commit-action@v4.1.6
      with:
        commit_message: Apply automatic changes

        # Optional name of the branch the commit should be pushed to
        # Required if Action is used in Workflow listening to the `pull_request` event.
        # Also required for almost all other events (eg. `schedule`)
        branch: ${{ github.head_ref }}

        # Optional git params
        commit_options: '--no-verify --signoff'

        # Optional glob pattern of files which should be added to the commit
        file_pattern: genproto/go/*.pb.go genproto/cs/*.cs

        # Optional local file path to the repository
        repository: .

        # Optional commit user and author settings
        commit_user_name: recluse-ci-robot
        commit_user_email: opensource@recluse-games.com
        commit_author: recluse-ci-robot <opensource@recluse-games.com>
