name: Update Consumer

on:
  push:
    paths:
      - 'genproto/cs/**/*'
      - 'genproto/go/**/*'
  pull_request:
    paths:
      - 'genproto/cs/**/*'
      - 'genproto/go/**/*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check-out the latest version of deviant-protobuf from GitHub
    - uses: actions/checkout@v2
      with:
        repository: recluse-games/deviant-protobuf
        path: deviant-protobuf
    
    # Check-out the latest version of deviant from GitHub
    - uses: actions/checkout@v2
      with: 
        repository: recluse-games/deviant
        path: deviant
        token: ${{ secrets.RECLUSE_CI_ROBOT_TOKEN }}

    # Download the latest built version of unity-meta-gen from artifacts
    - uses: actions/download-artifact@v2
      with:
        name: unity-meta-gen
        path: recluse-games/unity-meta-gen/build/unity-meta-gen

    # Generate Unity META files for new protobuf cs code
    - name: Generate Unity Metadata Files For Generated Protocol Buffers
      run: unity-meta-gen --type script deviant-protobuf/genproto/cs

    # Commit updated generated protobuf cs code in deviant package
    - name: Copy generated protocal buffers from deviant-protobuf to deviant
      run: cp -R deviant-protobuf/genproto/cs/. deviant/Assets/Scripts/Protobuf
    
    - uses: stefanzweifel/git-auto-commit-action@v4.1.6
      with:
        commit_message: Automatic Protocol Buffers Sync
        branch: ${{ github.head_ref }}
        commit_options: '--no-verify --signoff'
        file_pattern: Assets/Scripts/Protobuf/**/*
        repository: deviant
        commit_user_name: recluse-ci-robot
        commit_user_email: opensource@recluse-games.com
        commit_author: recluse-ci-robot <opensource@recluse-games.com>
